### ISSUE TITLE
L2 (trigger) not working

### ISSUE THREAD

**Issue by romkube** [dschu012/XOutputPlugin#1]
First, I'm not a experienced programmer, so it might come down to my poor scripting skills. I downloaded FreePIE and this plugin to play destiny through Xbox streaming to play with mouse and keyboard. But i cant get the L2 trigger to work, no matter how I try to bind it ("xoutput[0].L2" or "xoutput[0].L2 = xoutput[0].TriggerMax" )

Again, it could just be my poor scripting skills.

**Comment by dschu012** [comment]
Do the other buttons work? I figure something like

```
if keyboard.getKeyDown(Key.L)
    xoutput[0].L2 = xoutput[0].TriggerMax
```

would work. I can try and verify myself later. It isn't in the example script because I don't ever use that button in the game I wrote the script for.

**Comment by romkube** [comment]
L2 doesn't work at all. Tried all the different combinations I could think of and tested it. I've been reading through the code in XOutputPlugin.cs and noticed a difference between the R2 and L2 code ( line 171 to 181). Again, I'm not a coder, so it might be a good reason for this difference

```
   public int R2
    {
        get { return holder.GetTrigger(XOutputTrigger.R2); }
        set { holder.SetTrigger(XOutputTrigger.R2, value); }"
```

and 

```
  public int L2
    {
        get { return holder.GetAxis(XOutputAxis.RY); }
        set { holder.SetAxis(XOutputAxis.RY, value); }
```

**Comment by dschu012** [comment]
f534107c5e5a837b6ce649ac4f3039b6ea50c85c

The change above should fix it. Didn't test it, but you are correct in that it is wrong. There was lots of copying pasting for creating those functions for the buttons, guess I missed L2 when fixing all of them.

**Comment by romkube** [comment]
I tried changing the code and re-build the .dll at my computer. It fixed the problem with L2.
