### ISSUE TITLE
Freepie does not start with this plugin installed

### ISSUE THREAD

**Issue by Guibibi** [dschu012/XOutputPlugin#2]
So whenever I add your plugin in my plugins folder of my freepie, the program will start, but the GUI will not show up. But If I remove it, the program will start immediately and show the GUI.

**Comment by dschu012** [comment]
What version of FreePIE are you using?

**Comment by Guibibi** [comment]
I am using 1.9.611.0 but I fixed it by recompiling the project.

**Comment by rob19841** [comment]
i am having the same problem what version do i need. i have 1.9.629
